### ISSUE TITLE
[BUG] Cannot add dev tool panel

### ISSUE THREAD

**Issue by Elvincth** [sanyu1225/vue-cli-plugin-chrome-extension-cli#1]
After I added devtool.vue and its entry file, but seems it didn't auto gentrate the html and js files in /dist folder

![image](https://user-images.githubusercontent.com/6602723/120684423-3e750f00-c4d1-11eb-9c89-eb6e2642d018.png)

**Comment by sanyu1225** [comment]
This is a feature that I missed and will be corrected. It is expected to be updated tomorrow

**Comment by Elvincth** [comment]
Thanks looking forward to it 👍

**Comment by sanyu1225** [comment]
Sorry for some problems. The next version will be postponed before this weekend. 😓

**Comment by Elvincth** [comment]
No problem, thx

**Comment by sanyu1225** [comment]
new version is publish , now you can try it

**Comment by Elvincth** [comment]
Thanks for the work !!
