### ISSUE TITLE
vuetify

### ISSUE THREAD

**Issue by PabloRN** [sanyu1225/vue-cli-plugin-chrome-extension-cli#12]
I can't do vuetify works. Any tips?

**Comment by sanyu1225** [comment]
@PabloRN  please provide the vue-cli version, and the version that created vue
I can provide demo repo ,thx

**Comment by sanyu1225** [comment]
@PabloRN  , you can refer to [demo](https://github.com/sanyu1225/extension-demo/tree/main/vuetify)

**Comment by PabloRN** [comment]
Hey sanyu, thank you for the help. I will try it following the demo. Perhaps is because I'm using manifest version 3.

**Comment by sanyu1225** [comment]
ok, i will try manifest version 3
