### ISSUE TITLE
Chrome manifest 3 version

### ISSUE THREAD

**Issue by leodev87** [sanyu1225/vue-cli-plugin-chrome-extension-cli#14]
Greetings.
Sorry to bother you if it's not difficult I would like to get some answers to the newbie's questions.
environment:
- manifest 3 versions
- vue 2

The build works fine for production, but it's not clear how to develop.
"npm run serve" does not compile the files, it only starts the server.
"build-watch" doesn't work due to security policies

1. When working with 3 manifests, will you have to build and update the extension manually every time?
2. What are two manifests used for?
3. How to set up the plugin so that during development the cli does not compile files using eval? Or how to bypass this step during plugin development with version 3 manifest?

Thank you

**Comment by sanyu1225** [comment]
1. yes , it's bothers me
2. [manifest 3](https://developer.chrome.com/docs/extensions/mv3/intro/)  A step in the direction of security, privacy, and performance.
3. manifest_version 3 can't use ```npm run build-watch ```beacause version 3 can't support [CSP](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#content-security-policy)
There is currently no idea to bypass this rule , haha 
If you have better ideas, you can make reference suggestions

**Comment by Gsonovb** [comment]
HI , I found a way

https://stackoverflow.com/questions/67364003/use-vue3-and-vue-cli-to-develop-chrome-extension-how-to-hot-reload-the-code


vue.config.js
```

module.exports = {
  pages,
  filenameHashing: false,

  configureWebpack: {
    devtool: "inline-source-map",  //<<<here
    plugins: [
      CopyWebpackPlugin([
        {
          from: path.resolve(`src/manifest.${process.env.NODE_ENV}.json`),
          to: `${path.resolve("dist")}/manifest.json`,
        },
      ]),
    ],
    output: {
      filename: `js/[name].js`,
      chunkFilename: `[name].js`,
    },
  },
};

```

**Comment by sanyu1225** [comment]
Thank  [Gsonovb](https://github.com/Gsonovb) , [shadrachbaldon](https://github.com/shadrachbaldon) 
Now ,  support  use ```npm run build-watch```
