### ISSUE TITLE
Instruction on how to add more content scripts for different matches

### ISSUE THREAD

**Issue by masterprogrammer999** [sanyu1225/vue-cli-plugin-chrome-extension-cli#18]
Great project! Can you instruct me how to add more content scripts than one? I want one content script to match all sites, and another to match only a specific site. I know how I would do this with a vanilla Chrome Extenstion project, but not with vue.

**Comment by sanyu1225** [comment]
@masterprogrammer999  , you can refer to [demo](https://github.com/sanyu1225/extension-demo/tree/main/multipleContent)

I  add a [file](https://github.com/sanyu1225/extension-demo/blob/main/multipleContent/src/entry/contentForGoogle.js) in the entry folder 
And configure the relative url in manifest.*.json
Then ``npm run build`` will package all the files in the entry folder
