### ISSUE TITLE
Service workers have to be in root directory

### ISSUE THREAD

**Issue by TheSynt4x** [sanyu1225/vue-cli-plugin-chrome-extension-cli#24]
I stumbled across this bug last week. As per the [official documentation](https://developer.chrome.com/docs/extensions/mv3/service_workers/), you cannot have a service worker in a nested directory (which this extension plugin has). 

Whilst developing locally you will not run into any problems. It is in production, i.e. when it's published on Chrome Webstore that things don't work as intended. For me, several Chrome APIs did not work as intended, I couldn't for example call `chrome.tabs` even though I had the permission and such. 

The fix is quite simple. In `vue.config.js`, simply change `/js/[name].js` to `[name].js` in the `configureWebpack` object and re-build your extension.

**Comment by sanyu1225** [comment]
great,next version will fixed
