### ISSUE TITLE
怎么设图标？

### ISSUE THREAD

**Issue by fanghg2018** [sanyu1225/vue-cli-plugin-chrome-extension-cli#31]
打包后，没图标。

**Comment by Yacode** [comment]
我是这样处理的，在vue.config.js里面添加patterns规则，然后把图标放入public中
```javascript
{
  from: path.resolve(`public/`),
  to: `${path.resolve('dist')}/`
}
```

**Comment by sanyu1225** [comment]
Modified the deleted configuration and undeleted the public folder
Fix the problem that public is lost after packaging 
[new version ](https://github.com/sanyu1225/vue-cli-plugin-chrome-extension-cli/releases/tag/v1.1.4)
