### ISSUE TITLE
Hot Reload - Feature request

### ISSUE THREAD

**Issue by sherifmayika** [sanyu1225/vue-cli-plugin-chrome-extension-cli#36]
installed the app. amazing and fast. 
Please add Hot Reload

**Comment by sanyu1225** [comment]
[link](https://github.com/sanyu1225/vue-cli-plugin-chrome-extension-cli#run-development-mode-and-production)
You can refer to the document about the way of "Hot Reload" I have no other ideas for now, if you have better ideas can provide thank you haha

**Comment by sherifmayika** [comment]
thank you
I will update

**Comment by sherifmayika** [comment]
https://github.com/sanyu1225/extension-demo/tree/main/vuetify#user-content-compiles-and-hot-reloads-for-development
here I see hot reloads available on vuetify demo. is it limited to manifest v2?

**Comment by sherifmayika** [comment]
this project is MV3 with hot reloads
https://github.com/munron/mv3-vue-chrome-extension-template

**Comment by sherifmayika** [comment]
https://chrome.google.com/webstore/detail/advanced-extension-reload/hagknokdofkmojolcpbddjfdjhnjdkae
this look promising
