### ISSUE TITLE
copy inject scripts  - feature request

### ISSUE THREAD

**Issue by sherifmayika** [sanyu1225/vue-cli-plugin-chrome-extension-cli#38]
Is it already done?
Feature request:
copy (content script's) page inject JS and CSS to dist folder

**Comment by sanyu1225** [comment]
sure, if you generate extenstion template choose "content" it will work
but if you don't have choose "content" , you should add content.js file in ```/src/entry```
<img width="342" alt="image" src="https://user-images.githubusercontent.com/36758238/182657607-93814a8a-5a8e-41d9-ac4f-4c07cb30736d.png">

**Comment by sherifmayika** [comment]
thanks for the reply. 
I put my inject js in public. that also works. thanks. you 
you may close this
