### ISSUE TITLE
[BUG] multiple content file copied to "js" folder  and html file for content file

### ISSUE THREAD

**Issue by sherifmayika** [sanyu1225/vue-cli-plugin-chrome-extension-cli#40]
**Describe the bug**
1) copying multiple content files to js folder does not work. creates js.js file instead

2) creates html files for each content file

**To Reproduce**
1) 
added to vue.config,js
`const CopyWebpackPlugin = require("copy-webpack-plugin");` to top

and replaced 
```
  configureWebpack: {
    output: {
      filename: `js/[name].js`,
      chunkFilename: `[name].js`
    },
```

with this
```
  configureWebpack: {
    output: {
      filename: `js/[name].js`,
      chunkFilename: `[name].js`
    },
```
2) no chnges in vue.config.js

1. Use Vue cli create project 
```
Vue CLI v5.0.1
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, CSS Pre-processors, Linter
? Choose a version of Vue.js that you want to start the project with 2.x
? Use class-style component syntax? No
? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with dart-sass)
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```

2. Install chrome-extension-cli Plugin 
```
? Name of the Chrome Extension? chrome-extension-name
? Description for the Chrome Extension? chrome extension
? Version for the Chrome Extension? 0.0.1
? manifest_version for the Chrome Extension? 3
? delete Initial file? (src/main.js src/components public/index.html public/favicon) Yes
? Please select the required components : background, popup, content
```
5. See error ```something error...```

**Expected behavior**

**Screenshots**

***please complete the following information:***
 - Node Version: [16.14.0]
 - OS: [Mac OS Big Sur]
 - Vue Cli Version [5.0.1]

**Additional context**

**Comment by sherifmayika** [comment]
![20220807100104](https://user-images.githubusercontent.com/4177840/183275413-e4c0c032-b179-4907-8bf8-31c87bdef586.png)
![20220807100046](https://user-images.githubusercontent.com/4177840/183275415-ef2aacc8-fa5c-4740-ad29-02a4ac21c689.png)

**Comment by sherifmayika** [comment]
![20220807124153](https://user-images.githubusercontent.com/4177840/183279701-e071c931-f988-4fee-90f1-d134d2bb14fc.png)

**Comment by sanyu1225** [comment]
this plugin use fs.readdirSync function in entry folder.
so, other js file not recommend in this folder .
please create new foler put other js folder. 
because entry folder just generate extension file , like popup.html .

**Comment by sherifmayika** [comment]
> this plugin use fs.readdirSync function in entry folder. so, other js file not recommend in this folder . please create new foler put other js folder. because entry folder just generate extension file , like popup.html .

Thanks for the reply
Sorry 
I did not understand
