### ISSUE TITLE
[BUG] Unable to use images

### ISSUE THREAD

**Issue by frostcodes** [sanyu1225/vue-cli-plugin-chrome-extension-cli#42]
**Describe the bug**
When html < img > tag is used in popup page, it converts it from:

`
<img
          draggable="false"
          src="../../../assets/images/logo.png"
          width="100px"
          height="auto"
        />
`

TO:

`
<img draggable="false" src="/img/logo.png" width="0" height="0" />
`
in the browser

**To Reproduce**

1. Use Vue cli create project 
```
Vue CLI v5.0.8
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, CSS Pre-processors, Linter
? Choose a version of Vue.js that you want to start the project with 3.x
? Use class-style component syntax? No
? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with dart-sass)
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```

2. Install chrome-extension-cli Plugin 
```
? Name of the Chrome Extension? chrome-extension-name
? Description for the Chrome Extension? chrome extension
? Version for the Chrome Extension? 0.0.1
? manifest_version for the Chrome Extension? 3
? delete Initial file? (src/main.js src/components public/index.html public/favicon) Yes
? Please select the required components : background, popup, content
```
5. See error ```something error...```

**Expected behavior**
Image should show as typed in Vue file with attributes like height & width applied to it.

**Screenshots**

![image](https://user-images.githubusercontent.com/26607698/185526132-a40ae438-ab3d-4873-b6c4-ee33ed29d812.png)

***please complete the following information:***
 - Node Version: v16.7.0
 - OS: Windows
 - Vue Cli Version: 5.0.8

**Additional context**
NONE

**Comment by sanyu1225** [comment]
@frostcodes  it's not plugin bug, you can see [vue issue #3545 link](https://github.com/vuejs/core/issues/3545)
And Also recommend that you use alias in your src like "@/assets/logo.png"

**Comment by tinchox5** [comment]
IIt can be used style tag instead of attribute `style="width: 100%"`

**Comment by frostcodes** [comment]
> IIt can be used style tag instead of attribute `style="width: 100%"`

@sanyu1225 [answer ](https://github.com/sanyu1225/vue-cli-plugin-chrome-extension-cli/issues/42#issuecomment-1220271706) is the correct and recommended answer.
