### ISSUE TITLE
[Feature] Support projects created with `npm init vue@3`

### ISSUE THREAD

**Issue by 3210jr** [sanyu1225/vue-cli-plugin-chrome-extension-cli#43]
Hey @sanyu1225 

The project works well and as expected! Is there a plan to support projects created with the recommended `npm init vue@3` as opposed to using the older `vue create xxx` tool.

I tried using this extension on a new project created with `npm init vue@3` but the project would not run with the error:
```
Error: Cannot find module 'vue/compiler-sfc'
```

Thanks!
![Screenshot from 2022-08-23 20-49-00](https://user-images.githubusercontent.com/11012023/186324633-af7e6cf5-d05a-410f-9ef6-1e533935e108.png)

**Comment by sanyu1225** [comment]
Thank you feature, Sorry ```npm init vue@3``` is use ```vite``` not ```webpack```
This plugin extend [vue-cli](https://cli.vuejs.org/guide/plugins-and-presets.html#installing-plugins-in-an-existing-project)
