### ISSUE TITLE
i18n Internationalization Support

### ISSUE THREAD

**Issue by iriarte300** [sanyu1225/vue-cli-plugin-chrome-extension-cli#44]
Hi there! Is there a way to support internationalization? The problem I'm seeing is with the __locales_ folder which is required for internationalization to work. I believe the issue is that _locales does not get copied to _/dist_ so Chrome does not detected. I have tried creating this folder everywhere but no luck. Thanks!

REF: https://developer.chrome.com/docs/extensions/reference/i18n/

**Comment by sanyu1225** [comment]
Sure, you can move ```_locales``` folder to ```public``` folder it will work.
just like this ↓
![image](https://user-images.githubusercontent.com/36758238/187641853-99b2bf97-b8e6-4804-9be3-3a2302b34a8c.png)
