### ISSUE TITLE
background.service_worker manifest_version 3 error

### ISSUE THREAD

**Issue by simon28082** [sanyu1225/vue-cli-plugin-chrome-extension-cli#8]
Hi, 
Thank you very much for your contribution to the open source.
But I am in use, after installation, use Chrome to load the local plugin to report the following error:
The "background.scripts" key cannot be used with manifest_version 3. Use the "background.service_worker" key instead.
Could not load manifest.

ENV:
vue-cli4

**Comment by sanyu1225** [comment]
This is a feature that I missed and I will fix it soon.

**Comment by sanyu1225** [comment]
new version 1.0.8 is publish , now you can try it

**Comment by simon28082** [comment]
@sanyu1225 I'will retry it, thank you very much
